/******************************************************************************
*  Generated by PSoC Designer 5.1.2309
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "RX8_1.h"
#include "SPIM_1.h"
#include "TX8SW_1.h"
#include "Timer8_1.h"
#include "USBFS.h"

#endif
